export const ChangePostCategory ="ChangePostCategory";
export const GetPostSuccess ="GetPostSuccess";
export const add_post ="add_post";
export const add_post_image="add_post_image";
export const image="image";
export const add_user=  "add_user";
export const add_user_image="add_user_image";
export const update_user=  "update_user";
export const user_image="user_image";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const RESET_LOGIN = "RESET_LOGIN";
export const GET_USER_POST_SUCCESS = "GET_USER_POST_SUCCESS";
export const ChangeUserPostCategory ="ChangeUserPostCategory";
export const show_like_success ="show_like_success";
export const save_like_success ="save_like_success";
export const update_like_success ="update_like_success";
export const update_comment_success ="update_comment_success";
export const postId ="postId";
export const SET_CURRENT_USER ="SET_CURRENT_USER";
export const Notification_Success ="Notification_Success";
export const GET_USER="GET_USER"
export const search="search"
export const refresh="refresh"
export const refresh_delete="refresh_delete"
export const refresh_post="refresh_post"
export const ChangeUserProfilePostCategory ="ChangeUserProfilePostCategory";
export const GetUserProfile ="GetUserProfile";
export const GetUserProfilePostSuccess="GetUserProfilePostSuccess"
export const show_comment="show_comment"
export const add_comment="add_comment"
export const GetUserId="GetUserId"
export const POST_DELETE_SUCCESS="POST_DELETE_SUCCESS"
export const COMMENT_DELETE_SUCCESS="COMMENT_DELETE_SUCCESS"
export const GetCommentSuccess="GetCommentSuccess"
